#!/bin/bash

#check if the parameter
if [ "$1" = "--help" ]; then 
	echo -e " Script will inform you about weather in Minsk now.\n Information is taken from the 6.pogoda.by site.\n And the script is running in an infinite loop.\n  "
fi

#infinite loop
while [ true ]; do

	#Checking internet connection
	ping 6.pogoda.by -c 5 -w 15  &>/dev/null
	result=$?
	if [ "$result" -eq 2 ]; then
		echo "Could not resolve 6.pogoda.by"
		exit 1
	elif [ "$result" -eq 1 ]; then
		echo "Could not reach 6.pogoda.by"
		exit 2
	#else echo "Internet connection is successful"
	fi
 	#echo $result

	#get information about the weather
	list=$(curl http://6.pogoda.by/26850 -silent | grep '</h3><p>' | iconv -f WINDOWS-1251 -t UTF-8  | sed -e 's/<\/h3>//g' | sed -e 's/<p>/!\r/g' | sed -e 's/<br>&#9642;/\r/g' | sed -e 's/<h3>//g' | sed -e 's/&deg;//g' |  sed -e 's/<br>/\r/g' | sed -e 's/<\/p>//g' | sed -e 's/&nbsp;/ /g')

	echo -e "$list\n" >> pogoda
	#show notification
	notify-send "$list" "" -i gtk-about 

    	sleep 3
done

